// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/ismbond/v1/ismbond.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_bcp_innovations_hyperlane_cosmos_util "github.com/bcp-innovations/hyperlane-cosmos/util"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EvidenceKind is the slashing condition of spec §6.6 item 2.
type EvidenceKind int32

const (
	EVIDENCE_KIND_UNSPECIFIED EvidenceKind = 0
	// EQUIVOCATION: two checkpoints of the same (hook, index) with different roots signed by the same validator.
	EVIDENCE_KIND_EQUIVOCATION EvidenceKind = 1
	// INVALID_OUTBOUND: a signed checkpoint whose root differs from the recorded local root at that index.
	EVIDENCE_KIND_INVALID_OUTBOUND EvidenceKind = 2
)

var EvidenceKind_name = map[int32]string{
	0: "EVIDENCE_KIND_UNSPECIFIED",
	1: "EVIDENCE_KIND_EQUIVOCATION",
	2: "EVIDENCE_KIND_INVALID_OUTBOUND",
}

var EvidenceKind_value = map[string]int32{
	"EVIDENCE_KIND_UNSPECIFIED":      0,
	"EVIDENCE_KIND_EQUIVOCATION":     1,
	"EVIDENCE_KIND_INVALID_OUTBOUND": 2,
}

func (x EvidenceKind) String() string {
	return proto.EnumName(EvidenceKind_name, int32(x))
}

func (EvidenceKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c71b0636a4bcd66b, []int{0}
}

// Params defines the x/ismbond parameters (spec §6.6, Annex B).
type Params struct {
	// bond_min is the minimum bond of an operator (uluna).
	BondMin types.Coin `protobuf:"bytes,1,opt,name=bond_min,json=bondMin,proto3" json:"bond_min"`
	// unbond_delay_blocks is the wait between MsgUnbondOperator and MsgClaimBond (>= dispute window).
	UnbondDelayBlocks int64 `protobuf:"varint,2,opt,name=unbond_delay_blocks,json=unbondDelayBlocks,proto3" json:"unbond_delay_blocks,omitempty"`
	// dispute_window_blocks is how long outbound roots are kept for evidence.
	DisputeWindowBlocks int64 `protobuf:"varint,3,opt,name=dispute_window_blocks,json=disputeWindowBlocks,proto3" json:"dispute_window_blocks,omitempty"`
	// evidence_reward is the share of a slashed bond paid to the submitter.
	EvidenceReward cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=evidence_reward,json=evidenceReward,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"evidence_reward"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c71b0636a4bcd66b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBondMin() types.Coin {
	if m != nil {
		return m.BondMin
	}
	return types.Coin{}
}

func (m *Params) GetUnbondDelayBlocks() int64 {
	if m != nil {
		return m.UnbondDelayBlocks
	}
	return 0
}

func (m *Params) GetDisputeWindowBlocks() int64 {
	if m != nil {
		return m.DisputeWindowBlocks
	}
	return 0
}

// Operator is a bonded ISM validator.
type Operator struct {
	// address is the Terra Classic account that bonded.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// validator is the 20-byte ethereum-style address that signs checkpoints (lowercase hex, 0x-prefixed).
	Validator    string     `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Bond         types.Coin `protobuf:"bytes,3,opt,name=bond,proto3" json:"bond"`
	BondedHeight int64      `protobuf:"varint,4,opt,name=bonded_height,json=bondedHeight,proto3" json:"bonded_height,omitempty"`
	// unbond_height is the height at which the bond can be claimed (0 while active).
	UnbondHeight int64 `protobuf:"varint,5,opt,name=unbond_height,json=unbondHeight,proto3" json:"unbond_height,omitempty"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_c71b0636a4bcd66b, []int{1}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return m.Size()
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Operator) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *Operator) GetBond() types.Coin {
	if m != nil {
		return m.Bond
	}
	return types.Coin{}
}

func (m *Operator) GetBondedHeight() int64 {
	if m != nil {
		return m.BondedHeight
	}
	return 0
}

func (m *Operator) GetUnbondHeight() int64 {
	if m != nil {
		return m.UnbondHeight
	}
	return 0
}

// RootRecord is the root of the local merkle tree hook after an outbound
// message (spec §6.6: the chain knows its own state).
type RootRecord struct {
	MailboxId github_com_bcp_innovations_hyperlane_cosmos_util.HexAddress `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3,customtype=github.com/bcp-innovations/hyperlane-cosmos/util.HexAddress" json:"mailbox_id"`
	Index     uint32                                                      `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Root      []byte                                                      `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Height    int64                                                       `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *RootRecord) Reset()         { *m = RootRecord{} }
func (m *RootRecord) String() string { return proto.CompactTextString(m) }
func (*RootRecord) ProtoMessage()    {}
func (*RootRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c71b0636a4bcd66b, []int{2}
}
func (m *RootRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RootRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RootRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RootRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootRecord.Merge(m, src)
}
func (m *RootRecord) XXX_Size() int {
	return m.Size()
}
func (m *RootRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RootRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RootRecord proto.InternalMessageInfo

func (m *RootRecord) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RootRecord) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *RootRecord) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// Checkpoint is a signed Hyperlane checkpoint.
type Checkpoint struct {
	Origin         uint32                                                      `protobuf:"varint,1,opt,name=origin,proto3" json:"origin,omitempty"`
	MerkleTreeHook github_com_bcp_innovations_hyperlane_cosmos_util.HexAddress `protobuf:"bytes,2,opt,name=merkle_tree_hook,json=merkleTreeHook,proto3,customtype=github.com/bcp-innovations/hyperlane-cosmos/util.HexAddress" json:"merkle_tree_hook"`
	Root           []byte                                                      `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Index          uint32                                                      `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	MessageId      []byte                                                      `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// signature is the 65-byte ethereum signature of the checkpoint digest.
	Signature []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c71b0636a4bcd66b, []int{3}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return m.Size()
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetOrigin() uint32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *Checkpoint) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Checkpoint) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Checkpoint) GetMessageId() []byte {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *Checkpoint) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("terra.ismbond.v1.EvidenceKind", EvidenceKind_name, EvidenceKind_value)
	proto.RegisterType((*Params)(nil), "terra.ismbond.v1.Params")
	proto.RegisterType((*Operator)(nil), "terra.ismbond.v1.Operator")
	proto.RegisterType((*RootRecord)(nil), "terra.ismbond.v1.RootRecord")
	proto.RegisterType((*Checkpoint)(nil), "terra.ismbond.v1.Checkpoint")
}

func init() { proto.RegisterFile("terra/ismbond/v1/ismbond.proto", fileDescriptor_c71b0636a4bcd66b) }

var fileDescriptor_c71b0636a4bcd66b = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x15, 0x6d, 0xd9, 0x89, 0xa6, 0x76, 0xaa, 0x4c, 0xdc, 0x42, 0x76, 0x6b, 0xda, 0x50, 0x37,
	0x46, 0x00, 0x91, 0x95, 0xd3, 0x55, 0xba, 0xb2, 0x1e, 0x85, 0xd9, 0xa4, 0x52, 0xca, 0xd8, 0x2e,
	0x90, 0x0d, 0x31, 0xe4, 0x5c, 0x50, 0x03, 0x89, 0x33, 0xc2, 0xcc, 0x48, 0xb6, 0xff, 0xa0, 0xe8,
	0xaa, 0x9f, 0x50, 0x20, 0x3f, 0x50, 0x14, 0xf9, 0x88, 0x2c, 0x83, 0xac, 0x8a, 0x16, 0x08, 0x0a,
	0x7b, 0xd1, 0x7e, 0x43, 0x57, 0x05, 0x67, 0x46, 0xae, 0x05, 0x74, 0xd1, 0x45, 0x36, 0xd2, 0xdc,
	0x73, 0xce, 0xbd, 0xe4, 0x39, 0xbc, 0x24, 0xf2, 0x35, 0x48, 0x49, 0x42, 0xa6, 0x8a, 0x54, 0x70,
	0x1a, 0xce, 0xdb, 0x8b, 0x63, 0x30, 0x95, 0x42, 0x0b, 0x5c, 0x37, 0x7c, 0xb0, 0x00, 0xe7, 0xed,
	0x9d, 0xad, 0x5c, 0xe4, 0xc2, 0x90, 0x61, 0x79, 0xb2, 0xba, 0x9d, 0xed, 0x4c, 0xa8, 0x42, 0xa8,
	0xc4, 0x12, 0xb6, 0x70, 0xd4, 0x7d, 0x52, 0x30, 0x2e, 0x42, 0xf3, 0xeb, 0x20, 0xdf, 0x0a, 0xc2,
	0x94, 0x28, 0x08, 0xe7, 0xed, 0x14, 0x34, 0x69, 0x87, 0x99, 0x60, 0xdc, 0xf2, 0xcd, 0x97, 0x2b,
	0x68, 0xfd, 0x19, 0x91, 0xa4, 0x50, 0xf8, 0x31, 0xba, 0x5b, 0x5e, 0x39, 0x29, 0x18, 0x6f, 0x78,
	0xfb, 0xde, 0xc1, 0x07, 0x87, 0xdb, 0x81, 0x1b, 0x5f, 0x76, 0x07, 0xae, 0x3b, 0xe8, 0x0a, 0xc6,
	0x3b, 0xd5, 0xd7, 0xef, 0xf6, 0x2a, 0xf1, 0x9d, 0xb2, 0xe1, 0x1b, 0xc6, 0x71, 0x80, 0x1e, 0xcc,
	0xb8, 0xe9, 0xa6, 0x30, 0x21, 0x97, 0x49, 0x3a, 0x11, 0xd9, 0x58, 0x35, 0x56, 0xf6, 0xbd, 0x83,
	0xd5, 0xf8, 0xbe, 0xa5, 0x7a, 0x25, 0xd3, 0x31, 0x04, 0x3e, 0x44, 0x1f, 0x51, 0xa6, 0xa6, 0x33,
	0x0d, 0xc9, 0x39, 0xe3, 0x54, 0x9c, 0x2f, 0x3a, 0x56, 0x4d, 0xc7, 0x03, 0x47, 0x7e, 0x67, 0x38,
	0xd7, 0xf3, 0x02, 0x7d, 0x08, 0x73, 0x46, 0x81, 0x67, 0x90, 0x48, 0x38, 0x27, 0x92, 0x36, 0xaa,
	0xfb, 0xde, 0x41, 0xad, 0xd3, 0x2e, 0xef, 0xe5, 0xb7, 0x77, 0x7b, 0x9f, 0xd8, 0xbb, 0x55, 0x74,
	0x1c, 0x30, 0x11, 0x16, 0x44, 0x8f, 0x82, 0xa7, 0x90, 0x93, 0xec, 0xb2, 0x07, 0xd9, 0xdb, 0x57,
	0x2d, 0xe4, 0xcc, 0xf4, 0x20, 0x8b, 0xef, 0x2d, 0x26, 0xc5, 0x66, 0xd0, 0xe3, 0xdd, 0xbf, 0x7e,
	0xda, 0xf3, 0x7e, 0xf8, 0xf3, 0xe7, 0x87, 0x5b, 0xcb, 0x4f, 0xc9, 0x46, 0xd3, 0xfc, 0xdd, 0x43,
	0x77, 0x87, 0x53, 0x90, 0x44, 0x0b, 0x89, 0x0f, 0xd1, 0x1d, 0x42, 0xa9, 0x04, 0xa5, 0x4c, 0x4c,
	0xb5, 0x4e, 0xe3, 0xed, 0xab, 0xd6, 0x96, 0x1b, 0x7e, 0x64, 0x99, 0xe7, 0x5a, 0x32, 0x9e, 0xc7,
	0x0b, 0x21, 0xfe, 0x14, 0xd5, 0xe6, 0x64, 0xc2, 0x68, 0x39, 0xc0, 0xa4, 0x52, 0x8b, 0xff, 0x05,
	0xf0, 0x23, 0x54, 0x2d, 0xaf, 0x66, 0xcc, 0xff, 0x8f, 0xd4, 0x8d, 0x18, 0x7f, 0x86, 0x36, 0xcb,
	0x7f, 0xa0, 0xc9, 0x08, 0x58, 0x3e, 0xd2, 0x26, 0x8c, 0xd5, 0x78, 0xc3, 0x82, 0xc7, 0x06, 0x2b,
	0x45, 0xee, 0xb9, 0x38, 0xd1, 0x9a, 0x15, 0x59, 0xd0, 0x8a, 0x9a, 0xbf, 0x78, 0x08, 0xc5, 0x42,
	0xe8, 0x18, 0x32, 0x21, 0x29, 0x4e, 0x11, 0x2a, 0x08, 0x9b, 0xa4, 0xe2, 0x22, 0x61, 0xd4, 0x59,
	0xec, 0xba, 0x88, 0xbf, 0xcc, 0x99, 0x1e, 0xcd, 0xd2, 0x20, 0x13, 0x45, 0x98, 0x66, 0xd3, 0x16,
	0xe3, 0x5c, 0xcc, 0x89, 0x66, 0x82, 0xab, 0x70, 0x74, 0x39, 0x05, 0x39, 0x21, 0x1c, 0x5a, 0x6e,
	0xe7, 0x66, 0x9a, 0x4d, 0x82, 0x63, 0xb8, 0x70, 0x99, 0xc4, 0x35, 0x37, 0x36, 0xa2, 0x78, 0x0b,
	0xad, 0x31, 0x4e, 0xe1, 0xc2, 0x64, 0xb1, 0x19, 0xdb, 0x02, 0x63, 0x54, 0x95, 0x42, 0x68, 0x93,
	0xc3, 0x46, 0x6c, 0xce, 0xf8, 0x63, 0xb4, 0xbe, 0xe4, 0xcf, 0x55, 0xcd, 0xbf, 0x3d, 0x84, 0xba,
	0x23, 0xc8, 0xc6, 0x53, 0xc1, 0xb8, 0x91, 0x09, 0xc9, 0x72, 0xb7, 0xba, 0x9b, 0xb1, 0xab, 0x70,
	0x81, 0xea, 0x05, 0xc8, 0xf1, 0x04, 0x12, 0x2d, 0x01, 0x92, 0x91, 0x10, 0x63, 0x9b, 0xff, 0xfb,
	0xb1, 0x74, 0xcf, 0x0e, 0x3f, 0x91, 0x00, 0xc7, 0x42, 0x8c, 0xff, 0xd3, 0xc1, 0x8d, 0xd7, 0xea,
	0x6d, 0xaf, 0xbb, 0x08, 0x15, 0xa0, 0x14, 0xc9, 0xa1, 0x4c, 0x79, 0xcd, 0xe8, 0x6b, 0x0e, 0x89,
	0x68, 0xb9, 0x30, 0x8a, 0xe5, 0x9c, 0xe8, 0x99, 0x84, 0xc6, 0xba, 0x65, 0x6f, 0x80, 0x87, 0xe7,
	0x68, 0xa3, 0xef, 0x16, 0xf8, 0x09, 0xe3, 0x14, 0xef, 0xa2, 0xed, 0xfe, 0x59, 0xd4, 0xeb, 0x0f,
	0xba, 0xfd, 0xe4, 0x49, 0x34, 0xe8, 0x25, 0xa7, 0x83, 0xe7, 0xcf, 0xfa, 0xdd, 0xe8, 0xab, 0xa8,
	0xdf, 0xab, 0x57, 0xb0, 0x8f, 0x76, 0x96, 0xe9, 0xfe, 0xb7, 0xa7, 0xd1, 0xd9, 0xb0, 0x7b, 0x74,
	0x12, 0x0d, 0x07, 0x75, 0x0f, 0x37, 0x91, 0xbf, 0xcc, 0x47, 0x83, 0xb3, 0xa3, 0xa7, 0x51, 0x2f,
	0x19, 0x9e, 0x9e, 0x74, 0x86, 0xa7, 0x83, 0x5e, 0x7d, 0x65, 0xa7, 0xfa, 0xfd, 0x4b, 0xbf, 0xd2,
	0xf9, 0xfa, 0xf5, 0x95, 0xef, 0xbd, 0xb9, 0xf2, 0xbd, 0x3f, 0xae, 0x7c, 0xef, 0xc7, 0x6b, 0xbf,
	0xf2, 0xe6, 0xda, 0xaf, 0xfc, 0x7a, 0xed, 0x57, 0x5e, 0x7c, 0x7e, 0x2b, 0xc6, 0x6c, 0x42, 0x94,
	0x62, 0x59, 0xcb, 0xbe, 0x4b, 0x99, 0x90, 0x10, 0xce, 0xbf, 0x08, 0x2f, 0x6e, 0xde, 0x2a, 0x7d,
	0x39, 0x05, 0x95, 0xae, 0x9b, 0x2f, 0xd0, 0xa3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x31, 0x7d,
	0xce, 0xe1, 0x19, 0x05, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.BondMin.Equal(&that1.BondMin) {
		return false
	}
	if this.UnbondDelayBlocks != that1.UnbondDelayBlocks {
		return false
	}
	if this.DisputeWindowBlocks != that1.DisputeWindowBlocks {
		return false
	}
	if !this.EvidenceReward.Equal(that1.EvidenceReward) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.EvidenceReward.Size()
		i -= size
		if _, err := m.EvidenceReward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIsmbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.DisputeWindowBlocks != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.DisputeWindowBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.UnbondDelayBlocks != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.UnbondDelayBlocks))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.BondMin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIsmbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Operator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Operator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Operator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UnbondHeight != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.UnbondHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.BondedHeight != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.BondedHeight))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.Bond.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIsmbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintIsmbond(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintIsmbond(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RootRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RootRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RootRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintIsmbond(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Index != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.MailboxId.Size()
		i -= size
		if _, err := m.MailboxId.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIsmbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Checkpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Checkpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Checkpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintIsmbond(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MessageId) > 0 {
		i -= len(m.MessageId)
		copy(dAtA[i:], m.MessageId)
		i = encodeVarintIsmbond(dAtA, i, uint64(len(m.MessageId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Index != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintIsmbond(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.MerkleTreeHook.Size()
		i -= size
		if _, err := m.MerkleTreeHook.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIsmbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Origin != 0 {
		i = encodeVarintIsmbond(dAtA, i, uint64(m.Origin))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintIsmbond(dAtA []byte, offset int, v uint64) int {
	offset -= sovIsmbond(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BondMin.Size()
	n += 1 + l + sovIsmbond(uint64(l))
	if m.UnbondDelayBlocks != 0 {
		n += 1 + sovIsmbond(uint64(m.UnbondDelayBlocks))
	}
	if m.DisputeWindowBlocks != 0 {
		n += 1 + sovIsmbond(uint64(m.DisputeWindowBlocks))
	}
	l = m.EvidenceReward.Size()
	n += 1 + l + sovIsmbond(uint64(l))
	return n
}

func (m *Operator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovIsmbond(uint64(l))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovIsmbond(uint64(l))
	}
	l = m.Bond.Size()
	n += 1 + l + sovIsmbond(uint64(l))
	if m.BondedHeight != 0 {
		n += 1 + sovIsmbond(uint64(m.BondedHeight))
	}
	if m.UnbondHeight != 0 {
		n += 1 + sovIsmbond(uint64(m.UnbondHeight))
	}
	return n
}

func (m *RootRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MailboxId.Size()
	n += 1 + l + sovIsmbond(uint64(l))
	if m.Index != 0 {
		n += 1 + sovIsmbond(uint64(m.Index))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovIsmbond(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovIsmbond(uint64(m.Height))
	}
	return n
}

func (m *Checkpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Origin != 0 {
		n += 1 + sovIsmbond(uint64(m.Origin))
	}
	l = m.MerkleTreeHook.Size()
	n += 1 + l + sovIsmbond(uint64(l))
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovIsmbond(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovIsmbond(uint64(m.Index))
	}
	l = len(m.MessageId)
	if l > 0 {
		n += 1 + l + sovIsmbond(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovIsmbond(uint64(l))
	}
	return n
}

func sovIsmbond(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIsmbond(x uint64) (n int) {
	return sovIsmbond(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIsmbond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondMin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondMin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondDelayBlocks", wireType)
			}
			m.UnbondDelayBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondDelayBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeWindowBlocks", wireType)
			}
			m.DisputeWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeWindowBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EvidenceReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIsmbond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIsmbond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Operator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIsmbond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Operator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Operator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondedHeight", wireType)
			}
			m.BondedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondHeight", wireType)
			}
			m.UnbondHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIsmbond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIsmbond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RootRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIsmbond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RootRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RootRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MailboxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MailboxId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIsmbond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIsmbond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Checkpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIsmbond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Checkpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Checkpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			m.Origin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Origin |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleTreeHook", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MerkleTreeHook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageId = append(m.MessageId[:0], dAtA[iNdEx:postIndex]...)
			if m.MessageId == nil {
				m.MessageId = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIsmbond
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIsmbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIsmbond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIsmbond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIsmbond(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIsmbond
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIsmbond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIsmbond
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIsmbond
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIsmbond
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIsmbond        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIsmbond          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIsmbond = fmt.Errorf("proto: unexpected end of group")
)
