// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/batch/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SolverEscrowEntry is a solver escrow balance for genesis export.
type SolverEscrowEntry struct {
	Solver  string     `protobuf:"bytes,1,opt,name=solver,proto3" json:"solver,omitempty"`
	Balance types.Coin `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance"`
}

func (m *SolverEscrowEntry) Reset()         { *m = SolverEscrowEntry{} }
func (m *SolverEscrowEntry) String() string { return proto.CompactTextString(m) }
func (*SolverEscrowEntry) ProtoMessage()    {}
func (*SolverEscrowEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_81d4bb11af28f64e, []int{0}
}
func (m *SolverEscrowEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SolverEscrowEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SolverEscrowEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SolverEscrowEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolverEscrowEntry.Merge(m, src)
}
func (m *SolverEscrowEntry) XXX_Size() int {
	return m.Size()
}
func (m *SolverEscrowEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SolverEscrowEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SolverEscrowEntry proto.InternalMessageInfo

func (m *SolverEscrowEntry) GetSolver() string {
	if m != nil {
		return m.Solver
	}
	return ""
}

func (m *SolverEscrowEntry) GetBalance() types.Coin {
	if m != nil {
		return m.Balance
	}
	return types.Coin{}
}

// GenesisState defines the x/batch module's genesis state.
type GenesisState struct {
	Params            Params              `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Markets           []Market            `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets"`
	Intents           []Intent            `protobuf:"bytes,3,rep,name=intents,proto3" json:"intents"`
	NextIntentId      uint64              `protobuf:"varint,4,opt,name=next_intent_id,json=nextIntentId,proto3" json:"next_intent_id,omitempty"`
	Solvers           []Solver            `protobuf:"bytes,5,rep,name=solvers,proto3" json:"solvers"`
	SolverEscrows     []SolverEscrowEntry `protobuf:"bytes,6,rep,name=solver_escrows,json=solverEscrows,proto3" json:"solver_escrows"`
	Frontends         []Frontend          `protobuf:"bytes,7,rep,name=frontends,proto3" json:"frontends"`
	FrontendApprovals []FrontendApproval  `protobuf:"bytes,8,rep,name=frontend_approvals,json=frontendApprovals,proto3" json:"frontend_approvals"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_81d4bb11af28f64e, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMarkets() []Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

func (m *GenesisState) GetIntents() []Intent {
	if m != nil {
		return m.Intents
	}
	return nil
}

func (m *GenesisState) GetNextIntentId() uint64 {
	if m != nil {
		return m.NextIntentId
	}
	return 0
}

func (m *GenesisState) GetSolvers() []Solver {
	if m != nil {
		return m.Solvers
	}
	return nil
}

func (m *GenesisState) GetSolverEscrows() []SolverEscrowEntry {
	if m != nil {
		return m.SolverEscrows
	}
	return nil
}

func (m *GenesisState) GetFrontends() []Frontend {
	if m != nil {
		return m.Frontends
	}
	return nil
}

func (m *GenesisState) GetFrontendApprovals() []FrontendApproval {
	if m != nil {
		return m.FrontendApprovals
	}
	return nil
}

func init() {
	proto.RegisterType((*SolverEscrowEntry)(nil), "terra.batch.v1.SolverEscrowEntry")
	proto.RegisterType((*GenesisState)(nil), "terra.batch.v1.GenesisState")
}

func init() { proto.RegisterFile("terra/batch/v1/genesis.proto", fileDescriptor_81d4bb11af28f64e) }

var fileDescriptor_81d4bb11af28f64e = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x6b, 0x13, 0x41,
	0x14, 0xcf, 0x36, 0x31, 0x31, 0xd3, 0x1a, 0xc8, 0x50, 0x64, 0x1a, 0x64, 0x8d, 0xc5, 0x43, 0x10,
	0x3a, 0x63, 0xaa, 0x08, 0x05, 0x2f, 0x8d, 0x54, 0xed, 0x41, 0x91, 0x04, 0x2f, 0x5e, 0xc2, 0xec,
	0x66, 0xba, 0x5d, 0xcc, 0xce, 0x2c, 0xf3, 0xc6, 0xb5, 0xbd, 0xf9, 0x11, 0xfc, 0x18, 0x1e, 0x3d,
	0xf8, 0x21, 0x7a, 0x2c, 0x9e, 0x3c, 0x89, 0x24, 0x07, 0xbf, 0x84, 0x07, 0xd9, 0x99, 0x59, 0xac,
	0x21, 0xbd, 0x0c, 0xf3, 0xde, 0xef, 0xcf, 0x7b, 0xbc, 0xf7, 0xd0, 0x1d, 0x23, 0xb4, 0xe6, 0x2c,
	0xe2, 0x26, 0x3e, 0x65, 0xc5, 0x90, 0x25, 0x42, 0x0a, 0x48, 0x81, 0xe6, 0x5a, 0x19, 0x85, 0x3b,
	0x16, 0xa5, 0x16, 0xa5, 0xc5, 0xb0, 0xb7, 0x9d, 0xa8, 0x44, 0x59, 0x88, 0x95, 0x3f, 0xc7, 0xea,
	0x75, 0x79, 0x96, 0x4a, 0xc5, 0xec, 0xeb, 0x53, 0x3b, 0xb1, 0x82, 0x4c, 0xc1, 0xd4, 0x71, 0x5d,
	0xe0, 0xa1, 0xd0, 0x45, 0x2c, 0xe2, 0x20, 0x58, 0x31, 0x8c, 0x84, 0xe1, 0x43, 0x16, 0xab, 0x54,
	0x7a, 0xbc, 0xb7, 0xd2, 0x91, 0x2b, 0x6e, 0xb1, 0xdd, 0x4f, 0x01, 0xea, 0x4e, 0xd4, 0xbc, 0x10,
	0xfa, 0x08, 0x62, 0xad, 0x3e, 0x1e, 0x49, 0xa3, 0xcf, 0xf1, 0x43, 0xd4, 0x04, 0x9b, 0x24, 0x41,
	0x3f, 0x18, 0xb4, 0x47, 0xe4, 0xfb, 0xb7, 0xbd, 0x6d, 0x5f, 0xf3, 0x70, 0x36, 0xd3, 0x02, 0x60,
	0x62, 0x74, 0x2a, 0x93, 0xb1, 0xe7, 0xe1, 0x03, 0xd4, 0x8a, 0xf8, 0x9c, 0xcb, 0x58, 0x90, 0x8d,
	0x7e, 0x30, 0xd8, 0xdc, 0xdf, 0xa1, 0x9e, 0x5f, 0x76, 0x45, 0x7d, 0x57, 0xf4, 0x99, 0x4a, 0xe5,
	0xa8, 0x71, 0xf1, 0xf3, 0x6e, 0x6d, 0x5c, 0xf1, 0x77, 0xff, 0xd4, 0xd1, 0xd6, 0x0b, 0x37, 0xa4,
	0x89, 0xe1, 0x46, 0xe0, 0x03, 0xd4, 0xcc, 0xb9, 0xe6, 0x19, 0xd8, 0xea, 0x9b, 0xfb, 0xb7, 0xe9,
	0xff, 0x43, 0xa3, 0x6f, 0x2c, 0x3a, 0x6a, 0x97, 0x3e, 0x5f, 0x7e, 0x7f, 0x7d, 0x10, 0x8c, 0xbd,
	0x00, 0x3f, 0x41, 0xad, 0x8c, 0xeb, 0xf7, 0xc2, 0x00, 0xd9, 0xe8, 0xd7, 0xd7, 0x69, 0x5f, 0x59,
	0xb8, 0xea, 0xc1, 0x93, 0x4b, 0x5d, 0x2a, 0x8d, 0x90, 0x06, 0x48, 0x7d, 0xbd, 0xee, 0xd8, 0xc2,
	0x95, 0xce, 0x93, 0xf1, 0x7d, 0xd4, 0x91, 0xe2, 0xcc, 0x4c, 0x5d, 0x3c, 0x4d, 0x67, 0xa4, 0xd1,
	0x0f, 0x06, 0x8d, 0xf1, 0x56, 0x99, 0x75, 0x92, 0xe3, 0x59, 0xe9, 0xee, 0xc6, 0x04, 0xe4, 0xc6,
	0x7a, 0x77, 0xb7, 0x82, 0xca, 0xdd, 0x93, 0xf1, 0x6b, 0xd4, 0x71, 0xdf, 0xa9, 0xb0, 0xcb, 0x01,
	0xd2, 0xb4, 0xf2, 0x7b, 0xeb, 0xe5, 0x57, 0x36, 0xe8, 0x9d, 0x6e, 0xc1, 0x15, 0x00, 0xf0, 0x53,
	0xd4, 0x3e, 0xd1, 0xaa, 0xec, 0x6a, 0x06, 0xa4, 0x65, 0xad, 0xc8, 0xaa, 0xd5, 0x73, 0x4f, 0xf0,
	0x0e, 0xff, 0x04, 0xf8, 0x2d, 0xc2, 0x55, 0x30, 0xe5, 0x79, 0xae, 0x55, 0xc1, 0xe7, 0x40, 0x6e,
	0x5a, 0x9b, 0xfe, 0x75, 0x36, 0x87, 0x9e, 0xe8, 0xed, 0xba, 0x27, 0x2b, 0x79, 0x18, 0xbd, 0xbc,
	0x58, 0x84, 0xc1, 0xe5, 0x22, 0x0c, 0x7e, 0x2d, 0xc2, 0xe0, 0xf3, 0x32, 0xac, 0x5d, 0x2e, 0xc3,
	0xda, 0x8f, 0x65, 0x58, 0x7b, 0x47, 0x93, 0xd4, 0x9c, 0x7e, 0x88, 0x68, 0xac, 0x32, 0x16, 0xcf,
	0x39, 0x40, 0x1a, 0xef, 0xb9, 0x53, 0x8e, 0x95, 0x16, 0xac, 0x78, 0xcc, 0xce, 0xfc, 0x51, 0x9b,
	0xf3, 0x5c, 0x40, 0xd4, 0xb4, 0x27, 0xfd, 0xe8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xa5,
	0x68, 0x0c, 0x82, 0x03, 0x00, 0x00,
}

func (m *SolverEscrowEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SolverEscrowEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SolverEscrowEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Balance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Solver) > 0 {
		i -= len(m.Solver)
		copy(dAtA[i:], m.Solver)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Solver)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FrontendApprovals) > 0 {
		for iNdEx := len(m.FrontendApprovals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FrontendApprovals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Frontends) > 0 {
		for iNdEx := len(m.Frontends) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Frontends[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.SolverEscrows) > 0 {
		for iNdEx := len(m.SolverEscrows) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SolverEscrows[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Solvers) > 0 {
		for iNdEx := len(m.Solvers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Solvers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.NextIntentId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextIntentId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Intents) > 0 {
		for iNdEx := len(m.Intents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Intents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Markets) > 0 {
		for iNdEx := len(m.Markets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Markets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SolverEscrowEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Solver)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Balance.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Markets) > 0 {
		for _, e := range m.Markets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Intents) > 0 {
		for _, e := range m.Intents {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextIntentId != 0 {
		n += 1 + sovGenesis(uint64(m.NextIntentId))
	}
	if len(m.Solvers) > 0 {
		for _, e := range m.Solvers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SolverEscrows) > 0 {
		for _, e := range m.SolverEscrows {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Frontends) > 0 {
		for _, e := range m.Frontends {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FrontendApprovals) > 0 {
		for _, e := range m.FrontendApprovals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SolverEscrowEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SolverEscrowEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SolverEscrowEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Solver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Markets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Markets = append(m.Markets, Market{})
			if err := m.Markets[len(m.Markets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Intents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Intents = append(m.Intents, Intent{})
			if err := m.Intents[len(m.Intents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextIntentId", wireType)
			}
			m.NextIntentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextIntentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solvers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Solvers = append(m.Solvers, Solver{})
			if err := m.Solvers[len(m.Solvers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SolverEscrows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SolverEscrows = append(m.SolverEscrows, SolverEscrowEntry{})
			if err := m.SolverEscrows[len(m.SolverEscrows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frontends", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Frontends = append(m.Frontends, Frontend{})
			if err := m.Frontends[len(m.Frontends)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrontendApprovals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FrontendApprovals = append(m.FrontendApprovals, FrontendApproval{})
			if err := m.FrontendApprovals[len(m.FrontendApprovals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
