// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/liquidstake/v1/liquidstake.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the x/liquidstake parameters (spec §24, Annex B).
type Params struct {
	// epoch_blocks is the length of an epoch in blocks. It MUST satisfy
	// epoch_blocks * expected_block_time >= UnbondingTime / MaxEntries
	// (spec §24.4), checked against the live x/staking params in
	// MsgUpdateParams and InitGenesis. At runtime an epoch also never closes
	// before UnbondingTime / MaxEntries of block time has elapsed.
	EpochBlocks int64 `protobuf:"varint,1,opt,name=epoch_blocks,json=epochBlocks,proto3" json:"epoch_blocks,omitempty"`
	// fee_rate is the share of each epoch's uluna rewards taken as protocol fee (initial 5%).
	FeeRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=fee_rate,json=feeRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fee_rate"`
	// burn_share is the share of the fee burned directly in uluna (initial 20%, spec §23.1).
	BurnShare cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=burn_share,json=burnShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"burn_share"`
	// validator_cap is the maximum share of the module's delegations on one validator (initial 10%).
	ValidatorCap cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=validator_cap,json=validatorCap,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"validator_cap"`
	// max_share is the maximum share of the chain's bonded stake the module may hold (initial 20%).
	MaxShare cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=max_share,json=maxShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_share"`
	// buffer_ratio is the share of total assets kept undelegated for instant redemptions (initial 2%).
	BufferRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=buffer_ratio,json=bufferRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"buffer_ratio"`
	// max_commission excludes validators whose commission rate is above it.
	MaxCommission cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=max_commission,json=maxCommission,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_commission"`
	// min_uptime excludes validators whose signed ratio in the slashing window is below it.
	MinUptime cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=min_uptime,json=minUptime,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_uptime"`
	// max_validators bounds the number of validators the module delegates to per epoch.
	MaxValidators uint32 `protobuf:"varint,9,opt,name=max_validators,json=maxValidators,proto3" json:"max_validators,omitempty"`
	// expected_block_time is the block time assumed when checking the epoch
	// sizing rule (6s on mainnet). Bounded by MinExpectedBlockTime and
	// MaxExpectedBlockTime (non-governable constants).
	ExpectedBlockTime time.Duration `protobuf:"bytes,10,opt,name=expected_block_time,json=expectedBlockTime,proto3,stdduration" json:"expected_block_time"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_251effec65735fa8, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEpochBlocks() int64 {
	if m != nil {
		return m.EpochBlocks
	}
	return 0
}

func (m *Params) GetMaxValidators() uint32 {
	if m != nil {
		return m.MaxValidators
	}
	return 0
}

func (m *Params) GetExpectedBlockTime() time.Duration {
	if m != nil {
		return m.ExpectedBlockTime
	}
	return 0
}

// Epoch is the current epoch of the module.
type Epoch struct {
	Number      uint64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	StartHeight int64     `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	StartTime   time.Time `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
}

func (m *Epoch) Reset()         { *m = Epoch{} }
func (m *Epoch) String() string { return proto.CompactTextString(m) }
func (*Epoch) ProtoMessage()    {}
func (*Epoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_251effec65735fa8, []int{1}
}
func (m *Epoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Epoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Epoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Epoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Epoch.Merge(m, src)
}
func (m *Epoch) XXX_Size() int {
	return m.Size()
}
func (m *Epoch) XXX_DiscardUnknown() {
	xxx_messageInfo_Epoch.DiscardUnknown(m)
}

var xxx_messageInfo_Epoch proto.InternalMessageInfo

func (m *Epoch) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Epoch) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *Epoch) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

// UnstakeRequest is a queued redemption (spec §24.4).
type UnstakeRequest struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// st_amount is the amount of stLUNC burned when the request was accepted.
	StAmount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=st_amount,json=stAmount,proto3,customtype=cosmossdk.io/math.Int" json:"st_amount"`
	// amount is the uluna owed, fixed at the exchange rate of the request.
	Amount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	// epoch is the epoch in which the request was queued; it is undelegated at that epoch's end.
	Epoch uint64 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// completion_time is when the undelegation matures (zero until the batch is sent).
	CompletionTime time.Time `protobuf:"bytes,6,opt,name=completion_time,json=completionTime,proto3,stdtime" json:"completion_time"`
	// undelegated is true once the epoch batch that covers the request was sent.
	Undelegated bool `protobuf:"varint,7,opt,name=undelegated,proto3" json:"undelegated,omitempty"`
}

func (m *UnstakeRequest) Reset()         { *m = UnstakeRequest{} }
func (m *UnstakeRequest) String() string { return proto.CompactTextString(m) }
func (*UnstakeRequest) ProtoMessage()    {}
func (*UnstakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_251effec65735fa8, []int{2}
}
func (m *UnstakeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnstakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnstakeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnstakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnstakeRequest.Merge(m, src)
}
func (m *UnstakeRequest) XXX_Size() int {
	return m.Size()
}
func (m *UnstakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnstakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnstakeRequest proto.InternalMessageInfo

func (m *UnstakeRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnstakeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UnstakeRequest) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *UnstakeRequest) GetCompletionTime() time.Time {
	if m != nil {
		return m.CompletionTime
	}
	return time.Time{}
}

func (m *UnstakeRequest) GetUndelegated() bool {
	if m != nil {
		return m.Undelegated
	}
	return false
}

// ValidatorState records why a validator is (not) in the active set of the epoch.
type ValidatorState struct {
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	Eligible        bool   `protobuf:"varint,2,opt,name=eligible,proto3" json:"eligible,omitempty"`
	Reason          string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *ValidatorState) Reset()         { *m = ValidatorState{} }
func (m *ValidatorState) String() string { return proto.CompactTextString(m) }
func (*ValidatorState) ProtoMessage()    {}
func (*ValidatorState) Descriptor() ([]byte, []int) {
	return fileDescriptor_251effec65735fa8, []int{3}
}
func (m *ValidatorState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorState.Merge(m, src)
}
func (m *ValidatorState) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorState) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorState.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorState proto.InternalMessageInfo

func (m *ValidatorState) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *ValidatorState) GetEligible() bool {
	if m != nil {
		return m.Eligible
	}
	return false
}

func (m *ValidatorState) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "terra.liquidstake.v1.Params")
	proto.RegisterType((*Epoch)(nil), "terra.liquidstake.v1.Epoch")
	proto.RegisterType((*UnstakeRequest)(nil), "terra.liquidstake.v1.UnstakeRequest")
	proto.RegisterType((*ValidatorState)(nil), "terra.liquidstake.v1.ValidatorState")
}

func init() {
	proto.RegisterFile("terra/liquidstake/v1/liquidstake.proto", fileDescriptor_251effec65735fa8)
}

var fileDescriptor_251effec65735fa8 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xce, 0xe6, 0xc3, 0x59, 0x8f, 0x13, 0x97, 0x0e, 0x01, 0x6d, 0x83, 0xb0, 0x9d, 0x48, 0xa0,
	0x08, 0x94, 0x5d, 0xa5, 0xf4, 0xc4, 0xad, 0x49, 0x90, 0x5a, 0x29, 0x54, 0xd5, 0x26, 0xad, 0x10,
	0x97, 0xd5, 0xec, 0xee, 0xeb, 0xf5, 0x28, 0x3b, 0x3b, 0xdb, 0x99, 0x59, 0xcb, 0xfd, 0x05, 0x48,
	0x9c, 0x2a, 0xc4, 0x81, 0x23, 0x3f, 0x81, 0x43, 0x7e, 0x44, 0x8f, 0x55, 0x4e, 0x88, 0x43, 0x41,
	0xc9, 0x01, 0xc4, 0xaf, 0x40, 0xf3, 0x61, 0xe3, 0x36, 0xa7, 0xf8, 0x12, 0xe5, 0xfd, 0x7a, 0xfc,
	0xec, 0xfb, 0x3e, 0xcf, 0xa0, 0xcf, 0x15, 0x08, 0x41, 0xa2, 0x92, 0xbe, 0x68, 0x68, 0x2e, 0x15,
	0x39, 0x87, 0x68, 0x7c, 0x30, 0x1f, 0x86, 0xb5, 0xe0, 0x8a, 0xe3, 0x2d, 0xd3, 0x17, 0xce, 0x17,
	0xc6, 0x07, 0xdb, 0x5b, 0x05, 0x2f, 0xb8, 0x69, 0x88, 0xf4, 0x7f, 0xb6, 0x77, 0xfb, 0x5e, 0xc6,
	0x25, 0xe3, 0x32, 0xb1, 0x05, 0x1b, 0xb8, 0xd2, 0x5d, 0xc2, 0x68, 0xc5, 0x23, 0xf3, 0xd7, 0xa5,
	0xfa, 0x05, 0xe7, 0x45, 0x09, 0x91, 0x89, 0xd2, 0x66, 0x18, 0x29, 0xca, 0x40, 0x2a, 0xc2, 0x6a,
	0xd7, 0xd0, 0x7b, 0xbf, 0x21, 0x6f, 0x04, 0x51, 0x94, 0x57, 0xb6, 0xbe, 0xfb, 0x73, 0x0b, 0xb5,
	0x9e, 0x12, 0x41, 0x98, 0xc4, 0x3b, 0x68, 0x03, 0x6a, 0x9e, 0x8d, 0x92, 0xb4, 0xe4, 0xd9, 0xb9,
	0x0c, 0xbc, 0x81, 0xb7, 0xb7, 0x12, 0x77, 0x4c, 0xee, 0xd0, 0xa4, 0xf0, 0x09, 0xf2, 0x87, 0x00,
	0x89, 0x20, 0x0a, 0x82, 0xe5, 0x81, 0xb7, 0xd7, 0x3e, 0x3c, 0x78, 0xfd, 0xb6, 0xbf, 0xf4, 0xc7,
	0xdb, 0xfe, 0x27, 0x96, 0xa9, 0xcc, 0xcf, 0x43, 0xca, 0x23, 0x46, 0xd4, 0x28, 0x3c, 0x81, 0x82,
	0x64, 0x2f, 0x8f, 0x21, 0xbb, 0xbc, 0xd8, 0x47, 0xee, 0x43, 0x8e, 0x21, 0x8b, 0xd7, 0x87, 0x00,
	0x31, 0x51, 0x80, 0x9f, 0x22, 0x94, 0x36, 0xa2, 0x4a, 0xe4, 0x88, 0x08, 0x08, 0x56, 0x16, 0xc5,
	0x6b, 0x6b, 0x90, 0x53, 0x8d, 0x81, 0x9f, 0xa3, 0xcd, 0x31, 0x29, 0x69, 0x4e, 0x14, 0x17, 0x49,
	0x46, 0xea, 0x60, 0x75, 0x51, 0xd0, 0x8d, 0x19, 0xce, 0x11, 0xa9, 0xf1, 0x13, 0xd4, 0x66, 0x64,
	0xe2, 0x88, 0xae, 0x2d, 0x8a, 0xe9, 0x33, 0x32, 0xb1, 0x3c, 0xcf, 0xd0, 0x46, 0xda, 0x0c, 0x87,
	0x20, 0x12, 0x73, 0x8c, 0xa0, 0xb5, 0x28, 0x64, 0xc7, 0xc2, 0xc4, 0x1a, 0x05, 0x7f, 0x87, 0xba,
	0x9a, 0x65, 0xc6, 0x19, 0xa3, 0x52, 0x52, 0x5e, 0x05, 0xeb, 0x8b, 0xe2, 0x6e, 0x32, 0x32, 0x39,
	0x9a, 0xe1, 0xe8, 0x4b, 0x31, 0x5a, 0x25, 0x4d, 0xad, 0xe5, 0x15, 0xf8, 0x0b, 0x5f, 0x8a, 0xd1,
	0xea, 0x99, 0xc1, 0xc0, 0x9f, 0x59, 0xae, 0xb3, 0x2d, 0xcb, 0xa0, 0x3d, 0xf0, 0xf6, 0x36, 0xcd,
	0x0f, 0x3f, 0x9f, 0x25, 0xf1, 0x29, 0xfa, 0x10, 0x26, 0x35, 0x64, 0x0a, 0x72, 0x2b, 0xcb, 0xc4,
	0x30, 0x40, 0x03, 0x6f, 0xaf, 0x73, 0xff, 0x5e, 0x68, 0xc5, 0x1d, 0x4e, 0xc5, 0x1d, 0x1e, 0x3b,
	0x71, 0x1f, 0xfa, 0x9a, 0xdc, 0x2f, 0x7f, 0xf6, 0xbd, 0xf8, 0xee, 0x74, 0xde, 0x48, 0xf8, 0x8c,
	0x32, 0xf8, 0x7a, 0xe7, 0x9f, 0x5f, 0xfb, 0xde, 0x8f, 0x7f, 0xff, 0xf6, 0x45, 0x70, 0xd3, 0xbf,
	0xd6, 0x0b, 0xbb, 0x3f, 0x78, 0x68, 0xed, 0x1b, 0x2d, 0x7c, 0xfc, 0x31, 0x6a, 0x55, 0x0d, 0x4b,
	0x41, 0x18, 0x3f, 0xac, 0xc6, 0x2e, 0xd2, 0x6e, 0x91, 0x8a, 0x08, 0x95, 0x8c, 0x80, 0x16, 0x23,
	0x65, 0xec, 0xb0, 0x12, 0x77, 0x4c, 0xee, 0x91, 0x49, 0xe1, 0x23, 0x84, 0x6c, 0x8b, 0xe1, 0xbc,
	0x62, 0x38, 0x6f, 0xdf, 0xe0, 0x7c, 0x36, 0x75, 0xac, 0x25, 0xfd, 0x4a, 0x93, 0x6e, 0x9b, 0x39,
	0x5d, 0xd9, 0xfd, 0x77, 0x19, 0x75, 0x9f, 0x55, 0x86, 0x5c, 0x0c, 0x2f, 0x1a, 0x90, 0x0a, 0x77,
	0xd1, 0x32, 0xcd, 0x1d, 0x9d, 0x65, 0x9a, 0xe3, 0xfb, 0x68, 0x9d, 0xe4, 0xb9, 0x00, 0x29, 0x9d,
	0x29, 0x83, 0xcb, 0x8b, 0xfd, 0x2d, 0xb7, 0xf7, 0x87, 0xb6, 0x72, 0xaa, 0x04, 0xad, 0x8a, 0x78,
	0xda, 0x88, 0x1f, 0xa1, 0xb6, 0x54, 0x09, 0x61, 0xbc, 0xa9, 0x94, 0xb3, 0xde, 0x97, 0xee, 0xa0,
	0x1f, 0xdd, 0x3c, 0xe8, 0xe3, 0x4a, 0xcd, 0x9d, 0xf2, 0x71, 0xa5, 0x62, 0x5f, 0xaa, 0x87, 0x66,
	0x18, 0x1f, 0xa1, 0x96, 0x83, 0x59, 0xbd, 0x3d, 0x8c, 0x1b, 0xc5, 0x5b, 0x68, 0xcd, 0xbc, 0x33,
	0xc6, 0x5c, 0xab, 0xb1, 0x0d, 0xf0, 0xb7, 0xe8, 0x4e, 0xc6, 0x59, 0x5d, 0x82, 0xbe, 0xa9, 0xdd,
	0x62, 0xeb, 0x16, 0x5b, 0xec, 0xfe, 0x3f, 0xac, 0xcb, 0x78, 0x80, 0x3a, 0x4d, 0x95, 0x43, 0x09,
	0x05, 0x51, 0x90, 0x1b, 0x73, 0xf8, 0xf1, 0x7c, 0x6a, 0xf7, 0x27, 0x0f, 0x75, 0x67, 0xea, 0x3b,
	0x55, 0xfa, 0x91, 0x3a, 0x41, 0x1f, 0xf0, 0x1a, 0x84, 0x79, 0x51, 0xa6, 0x5b, 0xf6, 0xcc, 0x87,
	0xee, 0x5c, 0x5e, 0xec, 0x7f, 0xea, 0xbe, 0x65, 0x36, 0xf4, 0xee, 0xba, 0xef, 0x4c, 0x47, 0x5d,
	0x1a, 0x6f, 0x23, 0x1f, 0x4a, 0x5a, 0xd0, 0xb4, 0xb4, 0x0f, 0xa8, 0x1f, 0xcf, 0x62, 0xad, 0x34,
	0x01, 0x44, 0xf2, 0xca, 0xde, 0x23, 0x76, 0xd1, 0xe1, 0x93, 0xd7, 0x57, 0x3d, 0xef, 0xcd, 0x55,
	0xcf, 0xfb, 0xeb, 0xaa, 0xe7, 0xbd, 0xba, 0xee, 0x2d, 0xbd, 0xb9, 0xee, 0x2d, 0xfd, 0x7e, 0xdd,
	0x5b, 0xfa, 0xfe, 0x41, 0x41, 0xd5, 0xa8, 0x49, 0xc3, 0x8c, 0xb3, 0x28, 0x2b, 0x89, 0x94, 0x34,
	0xdb, 0xb7, 0x92, 0xce, 0xb8, 0x80, 0x68, 0xfc, 0x20, 0x9a, 0xbc, 0x23, 0x6e, 0xf5, 0xb2, 0x06,
	0x99, 0xb6, 0xcc, 0xd2, 0xbe, 0xfa, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x92, 0x3f, 0xc6, 0xbe,
	0x06, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochBlocks != that1.EpochBlocks {
		return false
	}
	if !this.FeeRate.Equal(that1.FeeRate) {
		return false
	}
	if !this.BurnShare.Equal(that1.BurnShare) {
		return false
	}
	if !this.ValidatorCap.Equal(that1.ValidatorCap) {
		return false
	}
	if !this.MaxShare.Equal(that1.MaxShare) {
		return false
	}
	if !this.BufferRatio.Equal(that1.BufferRatio) {
		return false
	}
	if !this.MaxCommission.Equal(that1.MaxCommission) {
		return false
	}
	if !this.MinUptime.Equal(that1.MinUptime) {
		return false
	}
	if this.MaxValidators != that1.MaxValidators {
		return false
	}
	if this.ExpectedBlockTime != that1.ExpectedBlockTime {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ExpectedBlockTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ExpectedBlockTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintLiquidstake(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	if m.MaxValidators != 0 {
		i = encodeVarintLiquidstake(dAtA, i, uint64(m.MaxValidators))
		i--
		dAtA[i] = 0x48
	}
	{
		size := m.MinUptime.Size()
		i -= size
		if _, err := m.MinUptime.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.MaxCommission.Size()
		i -= size
		if _, err := m.MaxCommission.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.BufferRatio.Size()
		i -= size
		if _, err := m.BufferRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MaxShare.Size()
		i -= size
		if _, err := m.MaxShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.ValidatorCap.Size()
		i -= size
		if _, err := m.ValidatorCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BurnShare.Size()
		i -= size
		if _, err := m.BurnShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.FeeRate.Size()
		i -= size
		if _, err := m.FeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.EpochBlocks != 0 {
		i = encodeVarintLiquidstake(dAtA, i, uint64(m.EpochBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Epoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Epoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Epoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintLiquidstake(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if m.StartHeight != 0 {
		i = encodeVarintLiquidstake(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.Number != 0 {
		i = encodeVarintLiquidstake(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UnstakeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnstakeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnstakeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Undelegated {
		i--
		if m.Undelegated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CompletionTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompletionTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintLiquidstake(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x32
	if m.Epoch != 0 {
		i = encodeVarintLiquidstake(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.StAmount.Size()
		i -= size
		if _, err := m.StAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLiquidstake(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Eligible {
		i--
		if m.Eligible {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidstake(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidstake(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochBlocks != 0 {
		n += 1 + sovLiquidstake(uint64(m.EpochBlocks))
	}
	l = m.FeeRate.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.BurnShare.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.ValidatorCap.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.MaxShare.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.BufferRatio.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.MaxCommission.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.MinUptime.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	if m.MaxValidators != 0 {
		n += 1 + sovLiquidstake(uint64(m.MaxValidators))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ExpectedBlockTime)
	n += 1 + l + sovLiquidstake(uint64(l))
	return n
}

func (m *Epoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 1 + sovLiquidstake(uint64(m.Number))
	}
	if m.StartHeight != 0 {
		n += 1 + sovLiquidstake(uint64(m.StartHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovLiquidstake(uint64(l))
	return n
}

func (m *UnstakeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLiquidstake(uint64(m.Id))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	l = m.StAmount.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	if m.Epoch != 0 {
		n += 1 + sovLiquidstake(uint64(m.Epoch))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompletionTime)
	n += 1 + l + sovLiquidstake(uint64(l))
	if m.Undelegated {
		n += 2
	}
	return n
}

func (m *ValidatorState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	if m.Eligible {
		n += 2
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	return n
}

func sovLiquidstake(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidstake(x uint64) (n int) {
	return sovLiquidstake(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochBlocks", wireType)
			}
			m.EpochBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BufferRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCommission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxCommission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinUptime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinUptime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValidators", wireType)
			}
			m.MaxValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxValidators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedBlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ExpectedBlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Epoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Epoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Epoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnstakeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnstakeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnstakeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Undelegated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Undelegated = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eligible", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Eligible = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidstake(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidstake
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidstake
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidstake
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidstake        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidstake          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidstake = fmt.Errorf("proto: unexpected end of group")
)
