// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/warpledger/v1/events.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventRecordSent is emitted when an outbound warp transfer is accounted.
type EventRecordSent struct {
	TokenId  string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Domain   uint32 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Amount   string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Sent     string `protobuf:"bytes,4,opt,name=sent,proto3" json:"sent,omitempty"`
	Received string `protobuf:"bytes,5,opt,name=received,proto3" json:"received,omitempty"`
	Exposure string `protobuf:"bytes,6,opt,name=exposure,proto3" json:"exposure,omitempty"`
}

func (m *EventRecordSent) Reset()         { *m = EventRecordSent{} }
func (m *EventRecordSent) String() string { return proto.CompactTextString(m) }
func (*EventRecordSent) ProtoMessage()    {}
func (*EventRecordSent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bdf782033e1d45c, []int{0}
}
func (m *EventRecordSent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRecordSent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRecordSent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRecordSent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRecordSent.Merge(m, src)
}
func (m *EventRecordSent) XXX_Size() int {
	return m.Size()
}
func (m *EventRecordSent) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRecordSent.DiscardUnknown(m)
}

var xxx_messageInfo_EventRecordSent proto.InternalMessageInfo

func (m *EventRecordSent) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *EventRecordSent) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *EventRecordSent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *EventRecordSent) GetSent() string {
	if m != nil {
		return m.Sent
	}
	return ""
}

func (m *EventRecordSent) GetReceived() string {
	if m != nil {
		return m.Received
	}
	return ""
}

func (m *EventRecordSent) GetExposure() string {
	if m != nil {
		return m.Exposure
	}
	return ""
}

// EventRecordReceived is emitted when an inbound warp transfer is accounted.
type EventRecordReceived struct {
	TokenId  string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Domain   uint32 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Amount   string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Sent     string `protobuf:"bytes,4,opt,name=sent,proto3" json:"sent,omitempty"`
	Received string `protobuf:"bytes,5,opt,name=received,proto3" json:"received,omitempty"`
	Exposure string `protobuf:"bytes,6,opt,name=exposure,proto3" json:"exposure,omitempty"`
}

func (m *EventRecordReceived) Reset()         { *m = EventRecordReceived{} }
func (m *EventRecordReceived) String() string { return proto.CompactTextString(m) }
func (*EventRecordReceived) ProtoMessage()    {}
func (*EventRecordReceived) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bdf782033e1d45c, []int{1}
}
func (m *EventRecordReceived) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRecordReceived) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRecordReceived.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRecordReceived) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRecordReceived.Merge(m, src)
}
func (m *EventRecordReceived) XXX_Size() int {
	return m.Size()
}
func (m *EventRecordReceived) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRecordReceived.DiscardUnknown(m)
}

var xxx_messageInfo_EventRecordReceived proto.InternalMessageInfo

func (m *EventRecordReceived) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *EventRecordReceived) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *EventRecordReceived) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *EventRecordReceived) GetSent() string {
	if m != nil {
		return m.Sent
	}
	return ""
}

func (m *EventRecordReceived) GetReceived() string {
	if m != nil {
		return m.Received
	}
	return ""
}

func (m *EventRecordReceived) GetExposure() string {
	if m != nil {
		return m.Exposure
	}
	return ""
}

// EventInvariantBroken is emitted in EndBlock when the local solvency
// invariant `BankBalance(warp, denom) >= sum of exposures` is violated
// (spec §9.3). Outbound transfers are tripped in x/circuit.
type EventInvariantBroken struct {
	Denom          string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	BankBalance    string `protobuf:"bytes,2,opt,name=bank_balance,json=bankBalance,proto3" json:"bank_balance,omitempty"`
	SumExposure    string `protobuf:"bytes,3,opt,name=sum_exposure,json=sumExposure,proto3" json:"sum_exposure,omitempty"`
	Height         int64  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	DisabledMsgUrl string `protobuf:"bytes,5,opt,name=disabled_msg_url,json=disabledMsgUrl,proto3" json:"disabled_msg_url,omitempty"`
}

func (m *EventInvariantBroken) Reset()         { *m = EventInvariantBroken{} }
func (m *EventInvariantBroken) String() string { return proto.CompactTextString(m) }
func (*EventInvariantBroken) ProtoMessage()    {}
func (*EventInvariantBroken) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bdf782033e1d45c, []int{2}
}
func (m *EventInvariantBroken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventInvariantBroken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventInvariantBroken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventInvariantBroken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventInvariantBroken.Merge(m, src)
}
func (m *EventInvariantBroken) XXX_Size() int {
	return m.Size()
}
func (m *EventInvariantBroken) XXX_DiscardUnknown() {
	xxx_messageInfo_EventInvariantBroken.DiscardUnknown(m)
}

var xxx_messageInfo_EventInvariantBroken proto.InternalMessageInfo

func (m *EventInvariantBroken) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *EventInvariantBroken) GetBankBalance() string {
	if m != nil {
		return m.BankBalance
	}
	return ""
}

func (m *EventInvariantBroken) GetSumExposure() string {
	if m != nil {
		return m.SumExposure
	}
	return ""
}

func (m *EventInvariantBroken) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EventInvariantBroken) GetDisabledMsgUrl() string {
	if m != nil {
		return m.DisabledMsgUrl
	}
	return ""
}

// EventMigrationSwept is emitted when a derived deposit address is swept
// through the native warp route (spec §10).
type EventMigrationSwept struct {
	TokenId        string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Domain         uint32 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Recipient      string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	DepositAddress string `protobuf:"bytes,4,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	Amount         string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee            string `protobuf:"bytes,6,opt,name=fee,proto3" json:"fee,omitempty"`
	MessageId      string `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (m *EventMigrationSwept) Reset()         { *m = EventMigrationSwept{} }
func (m *EventMigrationSwept) String() string { return proto.CompactTextString(m) }
func (*EventMigrationSwept) ProtoMessage()    {}
func (*EventMigrationSwept) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bdf782033e1d45c, []int{3}
}
func (m *EventMigrationSwept) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMigrationSwept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMigrationSwept.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMigrationSwept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMigrationSwept.Merge(m, src)
}
func (m *EventMigrationSwept) XXX_Size() int {
	return m.Size()
}
func (m *EventMigrationSwept) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMigrationSwept.DiscardUnknown(m)
}

var xxx_messageInfo_EventMigrationSwept proto.InternalMessageInfo

func (m *EventMigrationSwept) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *EventMigrationSwept) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *EventMigrationSwept) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *EventMigrationSwept) GetDepositAddress() string {
	if m != nil {
		return m.DepositAddress
	}
	return ""
}

func (m *EventMigrationSwept) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *EventMigrationSwept) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *EventMigrationSwept) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

// EventOriginPolicy is emitted when governance sets the share cap or pause
// flag of an origin of a basket token (spec §11.4 D-29).
type EventOriginPolicy struct {
	TokenId     string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Domain      uint32 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	ShareCap    string `protobuf:"bytes,3,opt,name=share_cap,json=shareCap,proto3" json:"share_cap,omitempty"`
	HasShareCap bool   `protobuf:"varint,4,opt,name=has_share_cap,json=hasShareCap,proto3" json:"has_share_cap,omitempty"`
	Paused      bool   `protobuf:"varint,5,opt,name=paused,proto3" json:"paused,omitempty"`
}

func (m *EventOriginPolicy) Reset()         { *m = EventOriginPolicy{} }
func (m *EventOriginPolicy) String() string { return proto.CompactTextString(m) }
func (*EventOriginPolicy) ProtoMessage()    {}
func (*EventOriginPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bdf782033e1d45c, []int{4}
}
func (m *EventOriginPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventOriginPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventOriginPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventOriginPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventOriginPolicy.Merge(m, src)
}
func (m *EventOriginPolicy) XXX_Size() int {
	return m.Size()
}
func (m *EventOriginPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_EventOriginPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_EventOriginPolicy proto.InternalMessageInfo

func (m *EventOriginPolicy) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *EventOriginPolicy) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *EventOriginPolicy) GetShareCap() string {
	if m != nil {
		return m.ShareCap
	}
	return ""
}

func (m *EventOriginPolicy) GetHasShareCap() bool {
	if m != nil {
		return m.HasShareCap
	}
	return false
}

func (m *EventOriginPolicy) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func init() {
	proto.RegisterType((*EventRecordSent)(nil), "terra.warpledger.v1.EventRecordSent")
	proto.RegisterType((*EventRecordReceived)(nil), "terra.warpledger.v1.EventRecordReceived")
	proto.RegisterType((*EventInvariantBroken)(nil), "terra.warpledger.v1.EventInvariantBroken")
	proto.RegisterType((*EventMigrationSwept)(nil), "terra.warpledger.v1.EventMigrationSwept")
	proto.RegisterType((*EventOriginPolicy)(nil), "terra.warpledger.v1.EventOriginPolicy")
}

func init() { proto.RegisterFile("terra/warpledger/v1/events.proto", fileDescriptor_5bdf782033e1d45c) }

var fileDescriptor_5bdf782033e1d45c = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xbd, 0x6e, 0xdb, 0x30,
	0x14, 0x85, 0xad, 0x3a, 0x76, 0x6c, 0xba, 0xf9, 0x29, 0x13, 0x04, 0xea, 0x9f, 0xe0, 0x7a, 0xa9,
	0x97, 0x5a, 0x08, 0xd2, 0x17, 0xa8, 0x8b, 0x0c, 0x1e, 0x8c, 0x16, 0x32, 0xba, 0x74, 0x11, 0x68,
	0xf1, 0x56, 0x22, 0x22, 0x91, 0x02, 0x49, 0x29, 0xc9, 0x5b, 0xf4, 0x0d, 0xba, 0x76, 0xe8, 0xd8,
	0x87, 0xe8, 0x98, 0x31, 0x63, 0x61, 0xbf, 0x48, 0x21, 0x8a, 0xb2, 0xdd, 0x35, 0x53, 0x36, 0x9e,
	0x8f, 0x97, 0xe0, 0x39, 0x97, 0xbc, 0x68, 0xa8, 0x41, 0x4a, 0xe2, 0x5f, 0x13, 0x99, 0xa7, 0x40,
	0x63, 0x90, 0x7e, 0x79, 0xee, 0x43, 0x09, 0x5c, 0xab, 0x49, 0x2e, 0x85, 0x16, 0xf8, 0xc4, 0x54,
	0x4c, 0xb6, 0x15, 0x93, 0xf2, 0x7c, 0xf4, 0xd3, 0x41, 0x47, 0x97, 0x55, 0x55, 0x00, 0x91, 0x90,
	0x74, 0x01, 0x5c, 0xe3, 0xe7, 0xa8, 0xa7, 0xc5, 0x15, 0xf0, 0x90, 0x51, 0xd7, 0x19, 0x3a, 0xe3,
	0x7e, 0xb0, 0x6f, 0xf4, 0x8c, 0xe2, 0x33, 0xd4, 0xa5, 0x22, 0x23, 0x8c, 0xbb, 0x4f, 0x86, 0xce,
	0xf8, 0x20, 0xb0, 0xaa, 0xe2, 0x24, 0x13, 0x05, 0xd7, 0x6e, 0xdb, 0x1c, 0xb0, 0x0a, 0x63, 0xb4,
	0xa7, 0x80, 0x6b, 0x77, 0xcf, 0x50, 0xb3, 0xc6, 0x2f, 0x50, 0x4f, 0x42, 0x04, 0xac, 0x04, 0xea,
	0x76, 0x0c, 0xdf, 0xe8, 0x6a, 0x0f, 0x6e, 0x72, 0xa1, 0x0a, 0x09, 0x6e, 0xb7, 0xde, 0x6b, 0xf4,
	0xe8, 0x97, 0x83, 0x4e, 0x76, 0xac, 0x06, 0xcd, 0x99, 0x47, 0x6a, 0xf7, 0xb7, 0x83, 0x4e, 0x8d,
	0xdd, 0x19, 0x2f, 0x89, 0x64, 0x84, 0xeb, 0xa9, 0xac, 0x6c, 0xe1, 0x53, 0xd4, 0xa1, 0xc0, 0x45,
	0x66, 0xcd, 0xd6, 0x02, 0xbf, 0x41, 0x4f, 0x97, 0x84, 0x5f, 0x85, 0x4b, 0x92, 0x12, 0x1e, 0x81,
	0x31, 0xdc, 0x0f, 0x06, 0x15, 0x9b, 0xd6, 0xa8, 0x2a, 0x51, 0x45, 0x16, 0x6e, 0x6e, 0xac, 0xbd,
	0x0f, 0x54, 0x91, 0x5d, 0x5a, 0x54, 0x05, 0x4b, 0x80, 0xc5, 0x49, 0x1d, 0xa1, 0x1d, 0x58, 0x85,
	0xc7, 0xe8, 0x98, 0x32, 0x45, 0x96, 0x29, 0xd0, 0x30, 0x53, 0x71, 0x58, 0xc8, 0xd4, 0x86, 0x39,
	0x6c, 0xf8, 0x5c, 0xc5, 0x5f, 0x64, 0x3a, 0xba, 0x6f, 0xba, 0x3c, 0x67, 0xb1, 0x24, 0x9a, 0x09,
	0xbe, 0xb8, 0x86, 0xfc, 0x41, 0x9f, 0xe2, 0x15, 0xea, 0x4b, 0x88, 0x58, 0xce, 0x60, 0xd3, 0xe8,
	0x2d, 0xc0, 0x6f, 0xd1, 0x11, 0x85, 0x5c, 0x28, 0xa6, 0x43, 0x42, 0xa9, 0x04, 0xa5, 0x6c, 0xdb,
	0x0f, 0x2d, 0xfe, 0x50, 0xd3, 0x9d, 0xc7, 0xea, 0xfc, 0xf7, 0x58, 0xc7, 0xa8, 0xfd, 0x0d, 0x9a,
	0xbe, 0x57, 0x4b, 0xfc, 0x1a, 0xa1, 0x0c, 0x94, 0x22, 0x31, 0x54, 0x2e, 0xf7, 0xeb, 0x1b, 0x2d,
	0x99, 0xd1, 0xd1, 0x0f, 0x07, 0x3d, 0x33, 0xd1, 0x3e, 0x49, 0x16, 0x33, 0xfe, 0x59, 0xa4, 0x2c,
	0xba, 0x7d, 0x48, 0xb0, 0x97, 0xa8, 0xaf, 0x12, 0x22, 0x21, 0x8c, 0x48, 0x6e, 0x83, 0xf5, 0x0c,
	0xf8, 0x48, 0x72, 0x3c, 0x42, 0x07, 0x09, 0x51, 0xe1, 0xb6, 0xa0, 0x4a, 0xd5, 0x0b, 0x06, 0x09,
	0x51, 0x8b, 0xa6, 0xe6, 0x0c, 0x75, 0x73, 0x52, 0x28, 0xfb, 0xa3, 0x7a, 0x81, 0x55, 0xd3, 0xf9,
	0x9f, 0x95, 0xe7, 0xdc, 0xad, 0x3c, 0xe7, 0xef, 0xca, 0x73, 0xbe, 0xaf, 0xbd, 0xd6, 0xdd, 0xda,
	0x6b, 0xdd, 0xaf, 0xbd, 0xd6, 0xd7, 0x8b, 0x98, 0xe9, 0xa4, 0x58, 0x4e, 0x22, 0x91, 0xf9, 0x51,
	0x4a, 0x94, 0x62, 0xd1, 0xbb, 0x7a, 0xe2, 0x23, 0x21, 0xc1, 0x2f, 0xdf, 0xfb, 0x37, 0xbb, 0xb3,
	0xaf, 0x6f, 0x73, 0x50, 0xcb, 0xae, 0x19, 0xfc, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf,
	0xbe, 0x57, 0x4c, 0x1c, 0x04, 0x00, 0x00,
}

func (m *EventRecordSent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRecordSent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRecordSent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Exposure) > 0 {
		i -= len(m.Exposure)
		copy(dAtA[i:], m.Exposure)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Exposure)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Received) > 0 {
		i -= len(m.Received)
		copy(dAtA[i:], m.Received)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Received)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Sent) > 0 {
		i -= len(m.Sent)
		copy(dAtA[i:], m.Sent)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Sent)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Domain != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRecordReceived) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRecordReceived) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRecordReceived) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Exposure) > 0 {
		i -= len(m.Exposure)
		copy(dAtA[i:], m.Exposure)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Exposure)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Received) > 0 {
		i -= len(m.Received)
		copy(dAtA[i:], m.Received)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Received)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Sent) > 0 {
		i -= len(m.Sent)
		copy(dAtA[i:], m.Sent)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Sent)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Domain != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventInvariantBroken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventInvariantBroken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventInvariantBroken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DisabledMsgUrl) > 0 {
		i -= len(m.DisabledMsgUrl)
		copy(dAtA[i:], m.DisabledMsgUrl)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.DisabledMsgUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Height != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if len(m.SumExposure) > 0 {
		i -= len(m.SumExposure)
		copy(dAtA[i:], m.SumExposure)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.SumExposure)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BankBalance) > 0 {
		i -= len(m.BankBalance)
		copy(dAtA[i:], m.BankBalance)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.BankBalance)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMigrationSwept) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMigrationSwept) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMigrationSwept) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageId) > 0 {
		i -= len(m.MessageId)
		copy(dAtA[i:], m.MessageId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MessageId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DepositAddress) > 0 {
		i -= len(m.DepositAddress)
		copy(dAtA[i:], m.DepositAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.DepositAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Domain != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventOriginPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventOriginPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventOriginPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.HasShareCap {
		i--
		if m.HasShareCap {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.ShareCap) > 0 {
		i -= len(m.ShareCap)
		copy(dAtA[i:], m.ShareCap)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ShareCap)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Domain != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventRecordSent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Domain != 0 {
		n += 1 + sovEvents(uint64(m.Domain))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Sent)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Received)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Exposure)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventRecordReceived) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Domain != 0 {
		n += 1 + sovEvents(uint64(m.Domain))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Sent)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Received)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Exposure)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventInvariantBroken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.BankBalance)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.SumExposure)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovEvents(uint64(m.Height))
	}
	l = len(m.DisabledMsgUrl)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventMigrationSwept) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Domain != 0 {
		n += 1 + sovEvents(uint64(m.Domain))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.DepositAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.MessageId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventOriginPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Domain != 0 {
		n += 1 + sovEvents(uint64(m.Domain))
	}
	l = len(m.ShareCap)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.HasShareCap {
		n += 2
	}
	if m.Paused {
		n += 2
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventRecordSent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRecordSent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRecordSent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Received", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Received = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exposure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Exposure = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRecordReceived) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRecordReceived: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRecordReceived: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Received", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Received = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exposure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Exposure = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventInvariantBroken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventInvariantBroken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventInvariantBroken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BankBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BankBalance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SumExposure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SumExposure = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisabledMsgUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisabledMsgUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMigrationSwept) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMigrationSwept: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMigrationSwept: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventOriginPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventOriginPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventOriginPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShareCap = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasShareCap", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasShareCap = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
