// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/warpledger/v1/warpledger.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_bcp_innovations_hyperlane_cosmos_util "github.com/bcp-innovations/hyperlane-cosmos/util"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the x/warpledger parameters.
type Params struct {
	// default_domain_cap is the net exposure cap applied to a (token, domain)
	// pair that has no explicit cap set by governance. Zero blocks outbound
	// transfers on such pairs until MsgSetDomainCap is executed.
	DefaultDomainCap cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=default_domain_cap,json=defaultDomainCap,proto3,customtype=cosmossdk.io/math.Int" json:"default_domain_cap"`
	// bonded_cap_threshold is the per-domain cap above which the token's ISM
	// must be bonded in x/ismbond (spec §7.2, §6.6). Zero disables the check.
	BondedCapThreshold cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=bonded_cap_threshold,json=bondedCapThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"bonded_cap_threshold"`
	// settle_source_cap is the default share of a basket token's circulation
	// that one origin domain may back (spec §11.4 D-29 item 4, initial 40%).
	// An origin whose share would exceed it refuses new deposits.
	SettleSourceCap cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=settle_source_cap,json=settleSourceCap,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"settle_source_cap"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_42fccdf8ca935bc6, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// DomainLedger is the per (warp token, remote domain) accounting record kept
// in consensus. Net exposure is `sent - received` (spec §9.1).
type DomainLedger struct {
	// token_id is the hyperlane id of the warp token (32-byte hex address).
	TokenId github_com_bcp_innovations_hyperlane_cosmos_util.HexAddress `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3,customtype=github.com/bcp-innovations/hyperlane-cosmos/util.HexAddress" json:"token_id"`
	// domain is the remote hyperlane domain id.
	Domain uint32 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// sent is the cumulative amount dispatched from Terra Classic to the domain.
	Sent cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=sent,proto3,customtype=cosmossdk.io/math.Int" json:"sent"`
	// received is the cumulative amount processed on Terra Classic from the domain.
	Received cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=received,proto3,customtype=cosmossdk.io/math.Int" json:"received"`
	// cap is the maximum allowed net exposure for the pair. Only meaningful when
	// has_cap is true; otherwise Params.default_domain_cap applies.
	Cap cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=cap,proto3,customtype=cosmossdk.io/math.Int" json:"cap"`
	// has_cap is true once governance has set an explicit cap for the pair.
	HasCap bool `protobuf:"varint,6,opt,name=has_cap,json=hasCap,proto3" json:"has_cap,omitempty"`
	// share_cap overrides Params.settle_source_cap for this origin of a basket
	// token (spec §11.4: origins without native issuance get a smaller cap).
	// Only meaningful when has_share_cap is true.
	ShareCap    cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=share_cap,json=shareCap,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"share_cap"`
	HasShareCap bool                        `protobuf:"varint,8,opt,name=has_share_cap,json=hasShareCap,proto3" json:"has_share_cap,omitempty"`
	// paused refuses new deposits from the origin and redemptions towards it
	// (spec §11.4 item 4: a failed or depegged origin is paused; item 6: a
	// paused origin is redeemed through the others).
	Paused bool `protobuf:"varint,9,opt,name=paused,proto3" json:"paused,omitempty"`
}

func (m *DomainLedger) Reset()         { *m = DomainLedger{} }
func (m *DomainLedger) String() string { return proto.CompactTextString(m) }
func (*DomainLedger) ProtoMessage()    {}
func (*DomainLedger) Descriptor() ([]byte, []int) {
	return fileDescriptor_42fccdf8ca935bc6, []int{1}
}
func (m *DomainLedger) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainLedger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainLedger.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainLedger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainLedger.Merge(m, src)
}
func (m *DomainLedger) XXX_Size() int {
	return m.Size()
}
func (m *DomainLedger) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainLedger.DiscardUnknown(m)
}

var xxx_messageInfo_DomainLedger proto.InternalMessageInfo

func (m *DomainLedger) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *DomainLedger) GetHasCap() bool {
	if m != nil {
		return m.HasCap
	}
	return false
}

func (m *DomainLedger) GetHasShareCap() bool {
	if m != nil {
		return m.HasShareCap
	}
	return false
}

func (m *DomainLedger) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "terra.warpledger.v1.Params")
	proto.RegisterType((*DomainLedger)(nil), "terra.warpledger.v1.DomainLedger")
}

func init() {
	proto.RegisterFile("terra/warpledger/v1/warpledger.proto", fileDescriptor_42fccdf8ca935bc6)
}

var fileDescriptor_42fccdf8ca935bc6 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe3, 0xb6, 0x38, 0xc9, 0x42, 0x05, 0x5d, 0x4a, 0x1b, 0x8a, 0xe4, 0x44, 0x11, 0x87,
	0xaa, 0x28, 0x36, 0x51, 0x39, 0x81, 0x10, 0xa2, 0x89, 0x04, 0x91, 0x0a, 0x42, 0x2e, 0x27, 0xa4,
	0xd6, 0xda, 0xec, 0x0e, 0xb1, 0x55, 0xdb, 0x6b, 0xed, 0x6e, 0x42, 0xf3, 0x0a, 0x9c, 0x78, 0x04,
	0x8e, 0x1c, 0x7b, 0xe0, 0x21, 0x72, 0xac, 0x38, 0x21, 0x0e, 0x15, 0x4a, 0x0e, 0xe5, 0x01, 0x78,
	0x00, 0xe4, 0x5d, 0x17, 0x22, 0xf5, 0x14, 0x2e, 0x51, 0x66, 0x77, 0xe6, 0xfb, 0x67, 0xe7, 0x1f,
	0xa3, 0xfb, 0x0a, 0x84, 0x20, 0xde, 0x07, 0x22, 0xb2, 0x18, 0xd8, 0x00, 0x84, 0x37, 0x6a, 0xcf,
	0x45, 0x6e, 0x26, 0xb8, 0xe2, 0xf8, 0xb6, 0xce, 0x72, 0xe7, 0xce, 0x47, 0xed, 0xad, 0xf5, 0x01,
	0x1f, 0x70, 0x7d, 0xef, 0xe5, 0xff, 0x4c, 0xea, 0xd6, 0x5d, 0xca, 0x65, 0xc2, 0x65, 0x60, 0x2e,
	0x4c, 0x50, 0x5c, 0xad, 0x91, 0x24, 0x4a, 0xb9, 0xa7, 0x7f, 0xcd, 0x51, 0x73, 0xb2, 0x84, 0xec,
	0x37, 0x44, 0x90, 0x44, 0xe2, 0x23, 0x84, 0x19, 0xbc, 0x27, 0xc3, 0x58, 0x05, 0x8c, 0x27, 0x24,
	0x4a, 0x03, 0x4a, 0xb2, 0x9a, 0xd5, 0xb0, 0xb6, 0xab, 0x7b, 0x0f, 0x27, 0xe7, 0xf5, 0xd2, 0x8f,
	0xf3, 0xfa, 0x1d, 0xc3, 0x93, 0xec, 0xd8, 0x8d, 0xb8, 0x97, 0x10, 0x15, 0xba, 0xbd, 0x54, 0x7d,
	0xfb, 0xda, 0x42, 0x85, 0x50, 0x2f, 0x55, 0x5f, 0x2e, 0x4e, 0x77, 0x2c, 0xff, 0x56, 0xc1, 0xea,
	0x6a, 0x54, 0x87, 0x64, 0xf8, 0x10, 0xad, 0xf7, 0x79, 0xca, 0x80, 0xe5, 0xdc, 0x40, 0x85, 0x02,
	0x64, 0xc8, 0x63, 0x56, 0x5b, 0xd2, 0x0a, 0x0f, 0x16, 0x50, 0xf0, 0xb1, 0x01, 0x75, 0x48, 0xf6,
	0xf6, 0x12, 0x83, 0x0f, 0xd1, 0x9a, 0x04, 0xa5, 0x62, 0x08, 0x24, 0x1f, 0x0a, 0x0a, 0xba, 0xfb,
	0x65, 0xcd, 0x6e, 0x17, 0xec, 0x7b, 0x57, 0xd9, 0xfb, 0x30, 0x20, 0x74, 0xdc, 0x05, 0x3a, 0xa7,
	0xd0, 0x05, 0xea, 0xdf, 0x34, 0xac, 0x03, 0x8d, 0xea, 0x90, 0xec, 0x71, 0xe3, 0xd7, 0xe7, 0xba,
	0xf5, 0xf1, 0xe2, 0x74, 0x67, 0xf3, 0x8a, 0x61, 0x66, 0x7e, 0xcd, 0xdf, 0xcb, 0xe8, 0x86, 0x79,
	0xed, 0xbe, 0x3e, 0xc7, 0x47, 0xa8, 0xa2, 0xf8, 0x31, 0xa4, 0x41, 0xc4, 0x8a, 0x31, 0x76, 0x8a,
	0x46, 0x9e, 0x0c, 0x22, 0x15, 0x0e, 0xfb, 0x2e, 0xe5, 0x89, 0xd7, 0xa7, 0x59, 0x2b, 0x4a, 0x53,
	0x3e, 0x22, 0x2a, 0xe2, 0xa9, 0xf4, 0xc2, 0x71, 0x06, 0x22, 0x26, 0x29, 0xb4, 0x4c, 0x3b, 0xde,
	0x50, 0x45, 0xb1, 0xfb, 0x12, 0x4e, 0x9e, 0x33, 0x26, 0x40, 0x4a, 0xbf, 0xac, 0xa1, 0x3d, 0x86,
	0x37, 0x90, 0x6d, 0x8c, 0xd2, 0x23, 0x5c, 0xf5, 0x8b, 0x08, 0x3f, 0x43, 0x2b, 0x12, 0x52, 0x55,
	0x3c, 0x7e, 0xa1, 0xc1, 0xea, 0x42, 0xfc, 0x02, 0x55, 0x04, 0x50, 0x88, 0x46, 0xc0, 0x6a, 0x2b,
	0x8b, 0x43, 0xfe, 0x16, 0xe3, 0xa7, 0x68, 0x39, 0x77, 0xe1, 0xda, 0xe2, 0x8c, 0xbc, 0x0e, 0x6f,
	0xa2, 0x72, 0x48, 0xa4, 0x36, 0xd2, 0x6e, 0x58, 0xdb, 0x15, 0xdf, 0x0e, 0x89, 0xcc, 0x57, 0xe9,
	0x35, 0xaa, 0xca, 0x90, 0x08, 0xe3, 0x71, 0xf9, 0x7f, 0x3d, 0xae, 0x68, 0x46, 0xce, 0x6b, 0xa2,
	0xd5, 0x5c, 0xe8, 0x1f, 0xb3, 0xa2, 0xe5, 0xae, 0x87, 0x44, 0x1e, 0x5c, 0xe6, 0x6c, 0x20, 0x3b,
	0x23, 0x43, 0x09, 0xac, 0x56, 0x35, 0xbd, 0x98, 0x68, 0xef, 0xd5, 0x64, 0xea, 0x58, 0x67, 0x53,
	0xc7, 0xfa, 0x39, 0x75, 0xac, 0x4f, 0x33, 0xa7, 0x74, 0x36, 0x73, 0x4a, 0xdf, 0x67, 0x4e, 0xe9,
	0xdd, 0xee, 0x9c, 0xcb, 0x34, 0x26, 0x52, 0x46, 0xb4, 0x65, 0x96, 0x87, 0x72, 0x01, 0xde, 0xe8,
	0x91, 0x77, 0x32, 0xbf, 0x46, 0x6a, 0x9c, 0x81, 0xec, 0xdb, 0xfa, 0xbb, 0xdc, 0xfd, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x21, 0xf1, 0x14, 0x5d, 0x18, 0x04, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DefaultDomainCap.Equal(that1.DefaultDomainCap) {
		return false
	}
	if !this.BondedCapThreshold.Equal(that1.BondedCapThreshold) {
		return false
	}
	if !this.SettleSourceCap.Equal(that1.SettleSourceCap) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SettleSourceCap.Size()
		i -= size
		if _, err := m.SettleSourceCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.BondedCapThreshold.Size()
		i -= size
		if _, err := m.BondedCapThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.DefaultDomainCap.Size()
		i -= size
		if _, err := m.DefaultDomainCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *DomainLedger) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainLedger) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainLedger) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.HasShareCap {
		i--
		if m.HasShareCap {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.ShareCap.Size()
		i -= size
		if _, err := m.ShareCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.HasCap {
		i--
		if m.HasCap {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.Cap.Size()
		i -= size
		if _, err := m.Cap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Received.Size()
		i -= size
		if _, err := m.Received.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Sent.Size()
		i -= size
		if _, err := m.Sent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Domain != 0 {
		i = encodeVarintWarpledger(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.TokenId.Size()
		i -= size
		if _, err := m.TokenId.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWarpledger(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintWarpledger(dAtA []byte, offset int, v uint64) int {
	offset -= sovWarpledger(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DefaultDomainCap.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	l = m.BondedCapThreshold.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	l = m.SettleSourceCap.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	return n
}

func (m *DomainLedger) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TokenId.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	if m.Domain != 0 {
		n += 1 + sovWarpledger(uint64(m.Domain))
	}
	l = m.Sent.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	l = m.Received.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	l = m.Cap.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	if m.HasCap {
		n += 2
	}
	l = m.ShareCap.Size()
	n += 1 + l + sovWarpledger(uint64(l))
	if m.HasShareCap {
		n += 2
	}
	if m.Paused {
		n += 2
	}
	return n
}

func sovWarpledger(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWarpledger(x uint64) (n int) {
	return sovWarpledger(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWarpledger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultDomainCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultDomainCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondedCapThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondedCapThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettleSourceCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SettleSourceCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWarpledger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWarpledger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DomainLedger) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWarpledger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainLedger: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainLedger: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Received", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Received.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasCap", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasCap = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarpledger
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWarpledger
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShareCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasShareCap", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasShareCap = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipWarpledger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWarpledger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWarpledger(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWarpledger
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWarpledger
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWarpledger
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWarpledger
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWarpledger
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWarpledger        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWarpledger          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWarpledger = fmt.Errorf("proto: unexpected end of group")
)
